# Generated by Django 5.2.8 on 2025-11-17 20:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('contact', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ex: COMPAGNON_180', max_length=50, unique=True)),
                ('nom', models.CharField(help_text='Ex: Compagnon', max_length=100)),
                ('pages', models.PositiveIntegerField(default=0)),
                ('prix_unitaire_defaut', models.DecimalField(decimal_places=2, help_text='Prix par défaut (peut être modifié par centre/période).', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ReleveCentreLivre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_periode', models.CharField(choices=[('WEEK', 'Semaine'), ('MONTH', 'Mois'), ('YEAR', 'Année')], max_length=10)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('quantite_recue', models.PositiveIntegerField(default=0)),
                ('quantite_vendue', models.PositiveIntegerField(default=0)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, help_text='Prix appliqué sur cette période.', max_digits=10)),
                ('depenses', models.DecimalField(decimal_places=2, default=0, help_text='Dépenses liées (transport, commissions...).', max_digits=10)),
                ('montant_ventes', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('quantite_reste', models.IntegerField(default=0, editable=False)),
                ('cree_le', models.DateTimeField(default=django.utils.timezone.now)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releves', to='gestion.centre')),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releves', to='gestion.livre')),
            ],
            options={
                'verbose_name': 'Relevé centre / livre',
                'verbose_name_plural': 'Relevés centre / livre',
                'unique_together': {('centre', 'livre', 'type_periode', 'date_debut', 'date_fin')},
            },
        ),
    ]
