# Generated by Django 5.2.8 on 2025-11-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_seed_initial_data'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='relevecentrelivre',
            unique_together={('centre', 'livre', 'date_debut', 'date_fin')},
        ),
        migrations.AddField(
            model_name='relevecentrelivre',
            name='montant_frais_retrait',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Frais de retrait calculés automatiquement à partir du taux.', max_digits=12),
        ),
        migrations.AddField(
            model_name='relevecentrelivre',
            name='operateur_mobile_money',
            field=models.CharField(blank=True, choices=[('MTN', 'MTN Money'), ('ORANGE', 'Orange Money'), ('MOOV', 'Moov Money'), ('WAVE', 'Wave')], help_text="Opérateur mobile money utilisé pour encaisser / retirer l'argent.", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='relevecentrelivre',
            name='taux_frais_retrait',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Taux des frais de retrait en %. Exemple : 1.5 pour 1,5%.', max_digits=5, null=True),
        ),
        migrations.RemoveField(
            model_name='relevecentrelivre',
            name='type_periode',
        ),
    ]
