# Generated by Django 5.2.8 on 2025-11-25 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_relevecentrelivre_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relevecentrelivre',
            name='taux_frais_retrait',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Taux des frais de retrait en %. Exemple : 1.5 pour 1,5%. Si laissé vide, il sera calculé automatiquement selon l'opérateur.", max_digits=5, null=True),
        ),
    ]
